'use client';
import {useEffect,useState} from 'react';
import {LayoutDashboard,MapPin,CarFront,ShieldCheck,Camera,ArrowUpRight,ArrowRight,ParkingSquare,Clock3,Bell,ChevronRight,Activity,ScanLine,Menu,RotateCcw,CheckCircle2,AlertTriangle,Play,Navigation} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Toaster,toast} from 'sonner';
import {Picker} from '@/components/parkwatch/controls';
import CameraView from '@/components/parkwatch/camera';
import Assistant from '@/components/parkwatch/assistant';
import {initialLots,counts,type Lot} from '@/lib/parking';
const nav=[{name:'Dashboard',icon:LayoutDashboard},{name:'Parking Lots',icon:MapPin},{name:'My Vehicle',icon:CarFront},{name:'Security',icon:ShieldCheck},{name:'AI Camera',icon:Camera}];
type Session={lot:string;spot:string;plate:string;end:number;warned:boolean};
type Alert={id:number;title:string;lot:string;spot:string;time:number;severity:string;read:boolean};
function getStored<T,>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}
function Stats({lots}:{lots:Lot[]}){const c=lots.reduce((a,l)=>{const c=counts(l);return{total:a.total+c.total,open:a.open+c.open,occupied:a.occupied+c.occupied,unknown:a.unknown+c.unknown}},{total:0,open:0,occupied:0,unknown:0});return <div className="stats-grid">{[{label:'Available spaces',value:c.open,icon:ParkingSquare,detail:'Across all 6 campus lots',tone:'green'},{label:'Occupied spaces',value:c.occupied,icon:CarFront,detail:`${Math.round(c.occupied/Math.max(c.total,1)*100)}% of mapped spaces`,tone:'red'},{label:'Mapped spaces',value:c.total,icon:MapPin,detail:c.unknown?`${c.unknown} need a closer look`:'Editable image calibration',tone:'blue'},{label:'Lots monitored',value:'06',icon:Camera,detail:'Still-image demo mode',tone:'purple'}].map(s=><section className="stat panel" key={s.label}><div className="stat-top"><span>{s.label}</span><div className={'stat-icon '+s.tone}><s.icon size={19}/></div></div><strong>{s.value}</strong><span className="small muted">{s.detail}</span></section>)}</div>}
function LotCard({lot,onClick}:{lot:Lot;onClick:()=>void}){const c=counts(lot),ratio=c.open/Math.max(c.total,1);return <button className="lot-card" onClick={onClick}><div className="lot-image"><img src={lot.image} alt={`Aerial view of ${lot.name}`}/><span className="lot-image-tag">{lot.source==='demo'?'DEMO DATA':'IMAGE ESTIMATE'}</span><span className="round-arrow"><ArrowUpRight size={17}/></span></div><div className="lot-card-body"><div className="between"><div><h3>{lot.name}</h3><span className="small muted">{lot.area}</span></div><span className={'availability '+(ratio>.3?'':'limited')}>{ratio>.3?'Spaces available':c.open?'Filling up':'No known openings'}</span></div><div className="lot-numbers"><strong>{c.open}<small> open</small></strong><span className="muted small">{c.occupied} occupied{c.unknown?` · ${c.unknown} review`:''}</span></div><div className="occupancy-bar"><div style={{width:c.open/Math.max(c.total,1)*100+'%'}}/></div><div className="between small muted"><span>{c.total} mapped spaces</span><span>View spaces <ChevronRight size={13}/></span></div></div></button>}
export default function Home(){
 const [page,setPage]=useState('Dashboard');const [lots,setLots]=useState<Lot[]>(initialLots);const [selected,setSelected]=useState('N');const [detail,setDetail]=useState(false);const [session,setSession]=useState<Session|null>(null);const [alerts,setAlerts]=useState<Alert[]>([]);const [ready,setReady]=useState(false);const [now,setNow]=useState(0);const [plate,setPlate]=useState('');const [vehicleLot,setVehicleLot]=useState('N');const [spot,setSpot]=useState('');const [duration,setDuration]=useState('120');const [filter,setFilter]=useState('all');
 useEffect(()=>{const saved=getStored<Lot[]>('pw-lots-v1',initialLots);if(Array.isArray(saved)&&saved.length===6&&saved.every(l=>Array.isArray(l.spots)))setLots(saved);setSession(getStored('pw-session',null));setAlerts(getStored('pw-alerts',[]));setNow(Date.now());setReady(true);const tick=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(tick)},[]);
 useEffect(()=>{if(ready){localStorage.setItem('pw-lots-v1',JSON.stringify(lots));localStorage.setItem('pw-session',JSON.stringify(session));localStorage.setItem('pw-alerts',JSON.stringify(alerts))}},[lots,session,alerts,ready]);
 useEffect(()=>{if(session&&now&&session.end-now<=15*60*1000&&!session.warned){toast.warning(session.end>now?'15 minutes or less remaining on your parking timer.':'Your parking timer has ended.');setSession({...session,warned:true})}},[now,session]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'get_parking_availability',description:'Read current ParkWatch lot counts and data sources; does not reserve a space.',inputSchema:{type:'object',properties:{lotId:{type:'string',enum:['E','F','G','M','N','R']}},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{if(input.lotId&&!lots.some(l=>l.id===input.lotId))throw new Error('Unknown lot');return lots.filter(l=>!input.lotId||l.id===input.lotId).map(l=>({id:l.id,source:l.source,...counts(l)}))}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[lots]);
 const go=(p:string)=>{setPage(p);setDetail(false)};const openLot=(id:string)=>{setSelected(id);setDetail(true);setPage('Parking Lots')};const lot=lots.find(l=>l.id===selected)!;const c=counts(lot);const remaining=session?Math.max(0,Math.ceil((session.end-now)/1000)):0;const timer=[Math.floor(remaining/3600),Math.floor(remaining%3600/60),remaining%60].map(n=>String(n).padStart(2,'0')).join(':');const unread=alerts.filter(a=>!a.read).length;
 const update=(lot:Lot)=>setLots(old=>old.map(l=>l.id===lot.id?lot:l));
 function simulate(){const id=Date.now();const l=session?.lot||selected;const s=session?.spot||lots.find(x=>x.id===l)!.spots[0]?.id||l+'-001';setAlerts(a=>[{id,title:a.length%2?'Unusual activity detected near your vehicle':'Possible impact detected near your vehicle',lot:l,spot:s,time:id,severity:a.length%2?'Medium':'High',read:false},...a]);toast.info('Simulated security event added.')}
 function startParking(e:React.FormEvent){e.preventDefault();const l=lots.find(l=>l.id===vehicleLot)!;if(!l.spots.some(s=>s.id===spot)){toast.error('Choose a parking space.');return}setSession({lot:vehicleLot,spot,plate:plate.trim().toUpperCase(),end:Date.now()+Number(duration)*60000,warned:false});toast.success('Parking timer started. This does not reserve the space.')}
 return <SidebarProvider><Toaster position="top-right" richColors/><Sidebar className="app-sidebar"><SidebarHeader className="brand"><div className="brand-icon"><ParkingSquare size={27}/></div><strong>ParkWatch<span>Campus parking, simplified</span></strong></SidebarHeader><SidebarContent><div className="nav-label">WORKSPACE</div><SidebarMenu className="nav-menu">{nav.map(n=><SidebarMenuItem key={n.name}><SidebarMenuButton isActive={page===n.name} onClick={()=>go(n.name)} className="nav-button"><n.icon size={19}/><span>{n.name}</span>{n.name==='Security'&&unread>0&&<b className="nav-count">{unread}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><div className="inline"><ScanLine size={19}/><b>Built for the next arrival.</b></div><p>Your campus parking,<br/>all in one place.</p><span className="tag">HACKATHON EDITION</span></div></SidebarContent><SidebarFooter className="sidebar-footer"><div className="avatar">SY</div><div><b>Skyline student</b><span>Campus community</span></div></SidebarFooter></Sidebar>
 <main className="main-shell"><header className="topbar"><div className="inline"><SidebarTrigger className="mobile-trigger"/><span className="campus-icon"><MapPin size={17}/></span><b>Skyline College</b><span className="top-divider"/><span className="muted">Campus parking</span></div><div className="inline"><span className="demo-pill"><i/>Demo environment</span><button className="icon-button notifications" aria-label={`Security notifications, ${unread} unread`} onClick={()=>go('Security')}><Bell size={20}/>{unread>0&&<i/>}</button><div className="avatar small-avatar">SY</div></div></header>
 <div className="workspace"><div className="page-heading"><div><div className="breadcrumb">Workspace <ChevronRight size={13}/> {page}</div><h1>{page==='Dashboard'?'A better way to park.':page==='Parking Lots'?(detail?lot.name+' · Space overview':'Explore campus parking'):page==='My Vehicle'?'Your vehicle. Your peace of mind.':page==='Security'?'A little extra peace of mind.':'A new perspective on parking.'}</h1><p className="muted">{page==='Dashboard'?'Find an open space and get on with your day.':page==='Parking Lots'?'See availability across campus before you head out.':page==='My Vehicle'?'Keep your parking details and time in one place.':page==='Security'?'Explore simulated vehicle-monitoring events.':'Turn your campus snapshots into parking insights.'}</p></div>{page==='Dashboard'&&<button className="primary" onClick={()=>go('Parking Lots')}><Navigation size={17}/>Find a space<ArrowRight size={16}/></button>}{page==='Security'&&<button className="primary" onClick={simulate}><Play size={16}/>Simulate event</button>}</div>
 {page==='Dashboard'&&<><Stats lots={lots}/><div className="dashboard-columns"><div><div className="section-heading"><div><h2>Campus parking lots <span className="count-badge">6</span></h2><p className="muted small">Your next space is closer than you think.</p></div><button className="text-button" onClick={()=>go('Parking Lots')}>View all lots<ArrowRight size={16}/></button></div><div className="lot-grid">{lots.map(l=><LotCard key={l.id} lot={l} onClick={()=>openLot(l.id)}/>)}</div></div><div className="dashboard-right"><Assistant lots={lots} onLot={openLot}/><section className="panel vehicle-mini"><div className="between"><h2>My parking</h2><CarFront size={20}/></div>{session?<><span className="small muted">Lot {session.lot} · {session.spot}</span><div className="mini-timer">{timer}</div><p className="small muted">Time remaining</p><button className="secondary full" onClick={()=>go('My Vehicle')}>Manage parking<ArrowRight size={15}/></button></>:<><div className="empty-car"><CarFront size={35}/></div><h3>Make yourself at home.</h3><p className="small muted">Parked already? Start a timer so you can focus on your day.</p><button className="secondary full" onClick={()=>go('My Vehicle')}>Add my vehicle<ArrowRight size={15}/></button></>}</section><div className="snapshot-note"><ShieldCheck size={21}/><p>Demo, with a purpose.<span>Still images and simulated events.<br/>No live surveillance or reservations.</span></p></div></div></div></>}
 {page==='Parking Lots'&&!detail&&<><div className="view-toolbar"><span className="small muted">6 lots · Select a lot to explore individual spaces</span><div className="legend"><span><i className="legend-dot green"/>Open</span><span><i className="legend-dot red"/>Occupied</span></div></div><div className="lot-grid all-lots">{lots.map(l=><LotCard key={l.id} lot={l} onClick={()=>openLot(l.id)}/>)}</div></>}
 {page==='Parking Lots'&&detail&&<><div className="view-toolbar"><button className="text-button" onClick={()=>setDetail(false)}>← All parking lots</button><Picker label="Choose lot" value={selected} onChange={setSelected} options={lots.map(l=>({value:l.id,label:l.name}))}/><span className="tag">{lot.source==='demo'?'SIMULATED COUNTS':'IMAGE ESTIMATES'}</span><button className="secondary" onClick={()=>setPage('AI Camera')}><Camera size={16}/>View image analysis</button></div><section className="panel space-panel"><div className="panel-head"><div><h2>{lot.area}</h2><p className="muted small">Schematic space grid · not a physical navigation map</p></div><div className="legend"><span><i className="legend-dot green"/>{c.open} open</span><span><i className="legend-dot red"/>{c.occupied} occupied</span><span><i className="legend-dot amber"/>{c.unknown} review</span></div></div><div className="space-grid">{lot.spots.map(s=><button key={s.id} className={'parking-space '+s.status} title={`${s.id}: ${s.status}. Start a timer for this space.`} onClick={()=>{setVehicleLot(lot.id);setSpot(s.id);setPage('My Vehicle')}}>{s.status==='occupied'?<CarFront size={20}/>:s.status==='open'?<ParkingSquare size={19}/>:<AlertTriangle size={18}/>}<span>{s.id}</span></button>)}</div><p className="muted small">Select your space to start a timer. A timer does not reserve a spot or change occupancy.</p></section></>}
 {page==='My Vehicle'&&<div className="vehicle-layout"><section className="panel vehicle-form"><div className="panel-head"><h2><CarFront size={21}/>Parking details</h2><span className="tag">THIS DEVICE ONLY</span></div><form onSubmit={startParking}><label>License plate <span className="muted">(optional)</span><input placeholder="e.g. 8ABC123" maxLength={15} value={plate} onChange={e=>setPlate(e.target.value)}/></label><label>Parking lot<Picker label="Parking lot" value={vehicleLot} onChange={v=>{setVehicleLot(v);setSpot('')}} options={lots.map(l=>({value:l.id,label:l.name+' · '+l.area}))}/></label><label>Parking space<Picker label="Parking space" value={spot} onChange={setSpot} options={lots.find(l=>l.id===vehicleLot)!.spots.map(s=>({value:s.id,label:s.id+' · '+s.status}))}/></label><label>Parking duration<Picker label="Parking duration" value={duration} onChange={setDuration} options={[['30','30 minutes'],['60','1 hour'],['120','2 hours'],['240','4 hours']].map(([value,label])=>({value,label}))}/></label><button className="primary full" disabled={!!session}><Clock3 size={17}/>{session?'Timer already running':'Start parking timer'}</button><p className="small muted">No plate needed. Choose your space and you’re set. Reminders appear while this app is open.</p></form></section><section className="panel timer-panel"><div className="timer-icon"><Clock3 size={28}/></div><span className="eyebrow">{session?'YOUR PARKING TIMER':'READY WHEN YOU ARE'}</span><div className={'big-timer '+(session&&remaining<=900?'timer-warning':'')}>{session?timer:'00:00:00'}</div><p className="muted">{session?(remaining?'Time remaining':'Your parking time has ended'):'Start a timer after you park.'}</p>{session&&<><div className="session-details"><b>Lot {session.lot} · {session.spot}</b><span>{session.plate||'No license plate added'}</span></div>{remaining<=900&&<div className="timer-notice"><Bell size={17}/>{remaining?'Your parking time is almost up.':'Parking timer ended.'}</div>}<button className="secondary full" onClick={()=>setSession(null)}>End parking session</button><button className="text-button" onClick={()=>{setNow(Date.now());setSession({...session,end:Date.now()+15*60000,warned:false})}}><Play size={14}/>Demo: jump to 15 minutes left</button></>}<p className="small muted">This is a reminder, not a parking permit.<br/>Follow the posted restrictions for your space.</p></section></div>}
 {page==='Security'&&<><div className="security-banner"><ShieldCheck size={27}/><div><b>Vehicle monitoring · simulation mode</b><p>No camera is watching your vehicle. These events demonstrate how future alerts could appear.</p></div></div><section className="panel"><div className="panel-head"><h2>Activity feed <span className="count-badge">{alerts.length}</span></h2><div className="inline"><Picker label="Filter security events" value={filter} onChange={setFilter} options={[{value:'all',label:'All events'},{value:'High',label:'High severity'},{value:'Medium',label:'Medium severity'}]}/><button className="text-button" onClick={()=>setAlerts(a=>a.map(x=>({...x,read:true})))}>Mark all read</button></div></div>{alerts.filter(a=>filter==='all'||a.severity===filter).length?alerts.filter(a=>filter==='all'||a.severity===filter).map(a=><div className={'alert-row '+(!a.read?'unread':'')} key={a.id}><div className={'alert-icon '+(a.severity==='High'?'red':'amber')}><AlertTriangle size={22}/></div><div className="alert-content"><h3>{a.title}</h3><p className="small muted">Lot {a.lot} · {a.spot} · {new Date(a.time).toLocaleString()}</p><span className="small muted">Simulated event · not a verified incident</span></div><span className={'tag '+(a.severity==='High'?'red-tag':'amber-tag')}>{a.severity}</span><button className="text-button" onClick={()=>setAlerts(old=>old.map(x=>x.id===a.id?{...x,read:true}:x))}>{a.read?'Reviewed':'Review'}</button></div>):<div className="empty-state"><ShieldCheck size={43}/><h3>Nothing to report.</h3><p className="muted">Simulate an event to explore the monitoring experience.</p><button className="secondary" onClick={simulate}><Play size={16}/>Create a demo alert</button></div>}</section></>}
 {page==='AI Camera'&&<CameraView lots={lots} selected={selected} setSelected={setSelected} update={update}/>}
 <footer className="page-footer"><span>ParkWatch <b>·</b> Made for campus life</span><a href="/ParkWatch-source.zip" download>Download project source ↗</a></footer></div></main></SidebarProvider>
}
