'use client';
import {useState} from 'react';
import {Sparkles,ArrowUp,ArrowUpRight} from 'lucide-react';
import {type Lot} from '@/lib/parking';
export default function Assistant({lots,onLot}:{lots:Lot[];onLot:(id:string)=>void}){
 const [query,setQuery]=useState('');const [reply,setReply]=useState<{text:string;lotId:string|null}|null>(null);const [busy,setBusy]=useState(false);
 async function ask(q:string){if(!q.trim()||busy)return;setBusy(true);setQuery('');try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,lots})});const data=await r.json() as {text:string;lotId:string|null;error?:string};if(!r.ok)throw new Error(data.error);setReply(data)}catch{setReply({text:'The parking assistant could not connect. Please try again.',lotId:null})}finally{setBusy(false)}}
 return <section className="assistant panel"><div className="inline"><div className="spark-icon"><Sparkles size={19}/></div><div><h2>Find your next spot</h2><span className="small muted">ParkWatch assistant</span></div><span className="tag assistant-tag">BETA</span></div><p className="assistant-copy">Less circling.<br/><strong>More getting there.</strong></p><p className="small muted">Ask which lot has the most room, or check a specific lot.</p>{reply&&<div className="assistant-answer" aria-live="polite">{reply.text}{reply.lotId&&<button className="text-button" onClick={()=>onLot(reply.lotId!)}>View Lot {reply.lotId}<ArrowUpRight size={15}/></button>}</div>}<button className="suggestion" onClick={()=>ask('Where should I park?')}>Where should I park?<ArrowUpRight size={15}/></button><form className="ask-form" onSubmit={e=>{e.preventDefault();ask(query)}}><input aria-label="Ask the parking assistant" placeholder="Ask about parking…" value={query} maxLength={2000} onChange={e=>setQuery(e.target.value)}/><button aria-label="Send question" disabled={busy||!query.trim()}><ArrowUp size={18}/></button></form><p className="micro muted">{busy?'Checking the latest app counts…':'Local recommendations · no external AI API'}</p></section>
}
