'use client';
import {useRef,useState} from 'react';
import {ScanLine,Plus,Trash2,Download,Check,Camera,MousePointer2} from 'lucide-react';
import {toast} from 'sonner';
import {Switch} from '@/components/ui/switch';
import {Picker} from './controls';
import {counts,extractFeatures,type Lot,type Spot,type Sample} from '@/lib/parking';
import seeds from '@/lib/seeds.json';
function loadImage(src:string):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Could not load the parking image.'));img.src=src})}
function features(img:HTMLImageElement,s:{x:number;y:number;w:number;h:number}){const canvas=document.createElement('canvas');canvas.width=16;canvas.height=16;const ctx=canvas.getContext('2d')!;ctx.drawImage(img,s.x*img.width,s.y*img.height,s.w*img.width,s.h*img.height,0,0,16,16);return extractFeatures(ctx.getImageData(0,0,16,16).data)}
export default function CameraView({lots,selected,setSelected,update}:{lots:Lot[];selected:string;setSelected:(v:string)=>void;update:(lot:Lot)=>void}){
 const lot=lots.find(l=>l.id===selected)!;const c=counts(lot);const [busy,setBusy]=useState(false);const [edit,setEdit]=useState(false);const [overlay,setOverlay]=useState(true);const [active,setActive]=useState<string|null>(null);const [adding,setAdding]=useState(false);const start=useRef<{x:number;y:number}|null>(null);const [draft,setDraft]=useState<{x:number;y:number;w:number;h:number}|null>(null);
 const chosen=lot.spots.find(s=>s.id===active);
 const change=(spots:Spot[])=>update({...lot,spots,source:'calibration edited',updatedAt:null});
 async function analyze(){setBusy(true);try{const images:Record<string,HTMLImageElement>={};for(const id of new Set([lot.id,...seeds.map(s=>s.lot),...lots.filter(l=>l.spots.some(s=>s.label)).map(l=>l.id)]))images[id]=await loadImage('/lots/'+id+'.png');const samples:Sample[]=seeds.map(s=>({features:features(images[s.lot],s),status:s.status as 'open'|'occupied'}));lots.forEach(l=>l.spots.filter(s=>s.label).forEach(s=>samples.push({features:features(images[l.id],s),status:s.label!})));const res=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({spots:lot.spots.map(s=>({id:s.id,features:features(images[lot.id],s)})),samples})});const result=await res.json() as {spots:Spot[];updatedAt:string;error?:string};if(!res.ok)throw new Error(result.error);update({...lot,source:'image estimate',updatedAt:result.updatedAt,spots:lot.spots.map(s=>({...s,...result.spots.find((r:Spot)=>r.id===s.id),...(s.label?{status:s.label,score:1}:{})}))});toast.success('Image analyzed. Dashboard and assistant updated.')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 function point(e:React.PointerEvent<HTMLDivElement>){const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 function download(){const blob=new Blob([JSON.stringify({version:1,lot:lot.id,image:lot.image,coordinateSystem:'normalized-xywh',spots:lot.spots},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`parkwatch-${lot.id}-annotations.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 return <><div className="view-toolbar"><div><span className="eyebrow">IMAGE ANALYSIS WORKSPACE</span><p>One snapshot. A clearer picture of parking.</p></div><Picker label="Camera lot" value={selected} onChange={v=>{setSelected(v);setActive(null)}} options={lots.map(l=>({value:l.id,label:l.name}))}/><button className="primary" onClick={analyze} disabled={busy||!lot.spots.length}><ScanLine size={17}/>{busy?'Analyzing image…':'Analyze image'}</button></div>
 <div className="camera-layout"><section className="panel camera-panel"><div className="panel-head"><div className="inline"><Camera size={18}/><h2>{lot.name} · Aerial snapshot</h2></div><span className="tag">STILL IMAGE</span></div><div className="image-workspace" style={{touchAction:adding?'none':'auto',cursor:adding?'crosshair':'default'}} onPointerDown={e=>{if(!adding)return;start.current=point(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!start.current)return;const p=point(e);setDraft({x:Math.min(p.x,start.current.x),y:Math.min(p.y,start.current.y),w:Math.abs(p.x-start.current.x),h:Math.abs(p.y-start.current.y)})}} onPointerUp={e=>{if(!start.current)return;const p=point(e),a=start.current;const d={x:Math.min(p.x,a.x),y:Math.min(p.y,a.y),w:Math.abs(p.x-a.x),h:Math.abs(p.y-a.y)};start.current=null;setDraft(null);if(d.w>.004&&d.h>.008){const id=lot.id+'-'+Date.now().toString().slice(-6);change([...lot.spots,{...d,id,status:'unknown'}]);setActive(id);setAdding(false)}}}>
 <img src={lot.image} alt={`Aerial image of campus parking ${lot.name}`} draggable={false}/>{overlay&&lot.spots.map(s=><button key={s.id} className={`detection ${s.status} ${active===s.id?'selected':''}`} style={{left:s.x*100+'%',top:s.y*100+'%',width:s.w*100+'%',height:s.h*100+'%'}} title={`${s.id}: ${s.status}`} aria-label={`${s.id}, ${s.status}`} onClick={()=>setActive(s.id)}><span>{s.status==='unknown'?'REVIEW':s.status.toUpperCase()}</span></button>)}{draft&&<div className="draw-box" style={{left:draft.x*100+'%',top:draft.y*100+'%',width:draft.w*100+'%',height:draft.h*100+'%'}}/>}{busy&&<div className="scan-beam"/>}</div><div className="camera-footer"><span><i className="status-dot"/> {lot.source==='demo'?'Demo overlay · simulated occupancy':'Image estimates · not live'}</span><label className="inline">Overlays <Switch checked={overlay} onCheckedChange={setOverlay}/></label></div></section>
 <aside className="panel analysis-panel"><span className="eyebrow">ANALYSIS RESULTS</span><div className="analysis-total">{c.total}<span>mapped spaces</span></div><div className="count-line"><span><i className="legend-dot green"/>Open</span><b>{c.open}</b></div><div className="count-line"><span><i className="legend-dot red"/>Occupied</span><b>{c.occupied}</b></div><div className="count-line"><span><i className="legend-dot amber"/>Needs review</span><b>{c.unknown}</b></div><hr/><h3>Prototype vision model</h3><p className="muted small">A 5-neighbor classifier compares image crops with labeled examples. The boxes are editable calibration templates, not automatically detected spaces.</p><span className="tag amber-tag">Accuracy not yet validated</span><p className="muted small">Counts cover mapped spaces only. Review trees, shadows, access aisles, and permit-only spaces before relying on results.</p>{lot.updatedAt&&<p className="small muted">Analyzed {new Date(lot.updatedAt).toLocaleTimeString()}</p>}</aside></div>
 <section className="panel calibration"><div className="panel-head"><div><h2>Calibrate & teach</h2><p className="muted small">Correct the boxes, then label examples to improve the next analysis.</p></div><button className="secondary" onClick={()=>{setEdit(!edit);setAdding(false)}}><MousePointer2 size={16}/>{edit?'Finish editing':'Edit mapped spaces'}</button></div>{edit&&<div className="calibration-body"><div className="inline wrap"><button className={adding?'primary':'secondary'} onClick={()=>{setAdding(!adding);setOverlay(true)}}><Plus size={16}/>{adding?'Drag a box on the image':'Draw new space'}</button><button className="secondary" onClick={download}><Download size={16}/>Export annotations</button><span className="muted small">Select a box to label or remove it. To resize a box, remove it and draw a replacement.</span></div>{chosen?<div className="label-editor"><b>{chosen.id}</b><button className="secondary" onClick={()=>change(lot.spots.map(s=>s.id===chosen.id?{...s,label:'open',status:'open'}:s))}><Check size={16}/>Label open</button><button className="secondary" onClick={()=>change(lot.spots.map(s=>s.id===chosen.id?{...s,label:'occupied',status:'occupied'}:s))}>Label occupied</button><button className="danger-btn" onClick={()=>{change(lot.spots.filter(s=>s.id!==chosen.id));setActive(null)}}><Trash2 size={16}/>Remove</button>{chosen.label&&<span className="tag">Labeled {chosen.label}</span>}</div>:<p className="muted small">Click a space in the image to review it.</p>}</div>}{!edit&&<div className="calibration-body small muted">{lots.reduce((n,l)=>n+l.spots.filter(s=>s.label).length,0)} user-labeled examples · 32 starter examples · Edits and results stay in this browser.</div>}</section></>;
}
